name: dotnet package

on:
  push:
    tags: [v*.*]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0']
    defaults:
      run:
        working-directory: ./protoc-gen-fsgrpc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDKs
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: |
            6.0.x
            8.0.x
      - name: Display version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build linux-arm64
        run: dotnet build -p:TargetFramework=net${{ matrix.dotnet-version }} --no-self-contained --configuration Release --no-restore -r linux-arm64
      - name: Build linux-x64
        run: dotnet build -p:TargetFramework=net${{ matrix.dotnet-version }} --no-self-contained --configuration Release --no-restore -r linux-x64
      - name: Build osx-x64
        run: dotnet build -p:TargetFramework=net${{ matrix.dotnet-version }} --no-self-contained --configuration Release --no-restore -r osx-x64
      - name: Build osx-arm64
        run: dotnet build -p:TargetFramework=net${{ matrix.dotnet-version }} --no-self-contained --configuration Release --no-restore -r osx-arm64
      - name: Build win-x86
        run: dotnet build -p:TargetFramework=net${{ matrix.dotnet-version }} --no-self-contained --configuration Release --no-restore -r win-x86
      - name: Build win-x64
        run: dotnet build -p:TargetFramework=net${{ matrix.dotnet-version }} --no-self-contained --configuration Release --no-restore -r win-x64
      - name: Package
        env:
          PROTOCGENFSGRPC_VERSION: ${{github.ref_name}}
        run: dotnet pack -p:PROTOCGENFSGRPC_VERSION=${PROTOCGENFSGRPC_VERSION#v} --no-restore --no-build --configuration Release
      - name: Nuget Push
        env:
          PROTOCGENFSGRPC_VERSION: ${{github.ref_name}}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push bin/Release/FsGrpc.ProtocGenFsGrpc.${PROTOCGENFSGRPC_VERSION#v}.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: GitHubRelease
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/Release/FsGrpc.ProtocGenFsGrpc.${PROTOCGENFSGRPC_VERSION#v}.nupkg


